substitutions:
  _REGION: us-central1
  _LOCATION: us-central1
  _REPO: apps
  _CLUSTER: cli-runner-gke
  _NAMESPACE: ws-cli
  _DOMAIN: ws.example.com
  _WS_DOMAIN: ws-gateway.example.com
  _BASENAME: ws-cli

options: { logging: CLOUD_LOGGING_ONLY }

steps:
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:470.0.0
  id: get-credentials
  entrypoint: bash
  args: ["-c", "gcloud container clusters get-credentials ${_CLUSTER} --region ${_LOCATION}"]

# Build runner image
- name: gcr.io/cloud-builders/docker
  id: build-runner
  dir: runner
  args: ["build","-t","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_BASENAME}-runner:$SHORT_SHA","."]
- name: gcr.io/cloud-builders/docker
  id: push-runner
  args: ["push","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_BASENAME}-runner:$SHORT_SHA"]
  waitFor: ["build-runner"]

# Build controller image
- name: gcr.io/cloud-builders/docker
  id: build-controller
  dir: controller
  args: ["build","-t","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_BASENAME}-controller:$SHORT_SHA","."]
- name: gcr.io/cloud-builders/docker
  id: push-controller
  args: ["push","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_BASENAME}-controller:$SHORT_SHA"]
  waitFor: ["build-controller"]

# Build ws-gateway image (NEW)
- name: gcr.io/cloud-builders/docker
  id: build-gateway
  dir: ws-gateway
  args: ["build","-t","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_BASENAME}-gateway:$SHORT_SHA","."]
- name: gcr.io/cloud-builders/docker
  id: push-gateway
  args: ["push","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_BASENAME}-gateway:$SHORT_SHA"]
  waitFor: ["build-gateway"]

# Apply Kubernetes manifests
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:470.0.0
  id: apply-k8s
  entrypoint: bash
  waitFor: ["push-runner", "push-controller", "push-gateway"]
  args:
  - -c
  - |
    set -euo pipefail
    kubectl apply -f k8s/namespace.yaml
    kubectl apply -f k8s/rbac.yaml
    kubectl apply -f k8s/networkpolicy.yaml
    kubectl apply -f k8s/resourcequota.yaml

    export CONTROLLER_IMG="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_BASENAME}-controller:$SHORT_SHA"
    export GATEWAY_IMG="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_BASENAME}-gateway:$SHORT_SHA"
    export RUNNER_IMG="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_BASENAME}-runner:$SHORT_SHA"
    export DOMAIN="${_DOMAIN}"
    export WS_DOMAIN="${_WS_DOMAIN}"

    envsubst < k8s/controller.yaml | kubectl apply -f -
    envsubst < k8s/gateway.yaml | kubectl apply -f -

    kubectl -n ${_NAMESPACE} rollout status deploy/ws-cli-controller --timeout=5m
    kubectl -n ${_NAMESPACE} rollout status deploy/ws-cli-gateway --timeout=5m

images:
- ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_BASENAME}-runner:$SHORT_SHA
- ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_BASENAME}-controller:$SHORT_SHA
- ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_BASENAME}-gateway:$SHORT_SHA