apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: cliscale

build:
  tagPolicy:
    gitCommit: {}

  # ⬇️ Be explicit about Cloud Build
  googleCloudBuild:
    projectId: cliscale
    # region: us-central1        # optional; default is global. Set if you use regional pools
    # timeout: 1200s             # optional
    # logging: CLOUD_LOGGING_ONLY

  artifacts:
    - image: controller
      context: controller
      docker:
        dockerfile: Dockerfile
    - image: gateway
      context: ws-gateway
      docker:
        dockerfile: Dockerfile
    - image: runner
      context: runner
      docker:
        dockerfile: Dockerfile

deploy:
  helm:
    releases:
      - name: cliscale
        chartPath: ./cliscale-chart
        namespace: ws-cli
        createNamespace: false
        setValueTemplates:
          controller.image.repository: "{{.IMAGE_REPO_controller}}"
          controller.image.tag: "{{.IMAGE_TAG_controller}}"
          gateway.image.repository: "{{.IMAGE_REPO_gateway}}"
          gateway.image.tag: "{{.IMAGE_TAG_gateway}}"
          controller.runnerImageURL: "{{.IMAGE_REPO_runner}}:{{.IMAGE_TAG_runner}}"

profiles:
  - name: dev
    build:
      tagPolicy:
        gitCommit: {}
      googleCloudBuild:
        projectId: cliscale
        # region: us-central1
      artifacts:
        - image: controller_dev
          context: controller
          docker:
            dockerfile: Dockerfile
        - image: gateway_dev
          context: ws-gateway
          docker:
            dockerfile: Dockerfile
        - image: runner_dev
          context: runner
          docker:
            dockerfile: Dockerfile
    deploy:
      helm:
        releases:
          - name: cliscale
            chartPath: ./cliscale-chart
            namespace: ws-cli
            createNamespace: false
            valuesFiles:
              - ./cliscale-chart/values-dev.yaml
            setValueTemplates:
              controller.image.repository: "{{.IMAGE_REPO_controller_dev}}"
              controller.image.tag: "{{.IMAGE_TAG_controller_dev}}"
              gateway.image.repository: "{{.IMAGE_REPO_gateway_dev}}"
              gateway.image.tag: "{{.IMAGE_TAG_gateway_dev}}"
              controller.runnerImageURL: "{{.IMAGE_REPO_runner_dev}}:{{.IMAGE_TAG_runner_dev}}"

  - name: prod
    build:
      tagPolicy:
        gitCommit: {}
      googleCloudBuild:
        projectId: cliscale
        # region: us-central1
      artifacts:
        - image: controller_prod
          context: controller
          docker:
            dockerfile: Dockerfile
        - image: gateway_prod
          context: ws-gateway
          docker:
            dockerfile: Dockerfile
        - image: runner_prod
          context: runner
          docker:
            dockerfile: Dockerfile
    deploy:
      helm:
        releases:
          - name: cliscale
            chartPath: ./cliscale-chart
            namespace: ws-cli
            createNamespace: false
            valuesFiles:
              - ./cliscale-chart/values-prod.yaml
            setValueTemplates:
              controller.image.repository: "{{.IMAGE_REPO_controller_prod}}"
              controller.image.tag: "{{.IMAGE_TAG_controller_prod}}"
              gateway.image.repository: "{{.IMAGE_REPO_gateway_prod}}"
              gateway.image.tag: "{{.IMAGE_TAG_gateway_prod}}"
              controller.runnerImageURL: "{{.IMAGE_REPO_runner_prod}}:{{.IMAGE_TAG_runner_prod}}"
