{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cliscale.fullname" . }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "gce"
    {{- if .Values.gateway.backendConfig.enabled }}
    cloud.google.com/backend-config: '{"ports": {"80": "{{ include "cliscale.fullname" . }}-gateway-backendconfig"}}'
    {{- end }}
spec:
  {{- if and .Values.ingress.tls.enabled .Values.ingress.hostname }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    {{- if .Values.ingress.hostname }}
    - host: {{ .Values.ingress.hostname }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          # WebSocket terminal routes (must be first for specific matching)
          - path: /ws/*
            pathType: Prefix
            backend:
              service:
                name: {{ include "cliscale.fullname" . }}-gateway
                port:
                  number: 80
          # API routes to controller
          - path: /api/*
            pathType: Prefix
            backend:
              service:
                name: {{ include "cliscale.fullname" . }}-controller
                port:
                  number: 80
          # JWKS endpoint (for JWT verification)
          - path: /.well-known/*
            pathType: Prefix
            backend:
              service:
                name: {{ include "cliscale.fullname" . }}-controller
                port:
                  number: 80
          # Default: route everything else to controller
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "cliscale.fullname" . }}-controller
                port:
                  number: 80
{{- end }}
