{{- range $svc, $cfg := .Values }}
{{- if and (kindIs "map" $cfg) (hasKey $cfg "networkPolicy") (get $cfg.networkPolicy "enabled") }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cliscale.fullnameFor" (list $ $svc) }}
spec:
  podSelector:
    matchLabels:
      {{- include "cliscale.selectorLabelsFor" (list $ $svc) | nindent 6 }}
  policyTypes:
{{ toYaml ($cfg.networkPolicy.policyTypes | default (list "Ingress")) | nindent 2 }}
  {{- with $cfg.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $cfg.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
