{{- range $compName, $comp := .Values.components }}
{{- $ns := $.Release.Namespace }}

{{- if $comp.rbac.create }}

{{- if $comp.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-%s" $.Release.Name $compName) $comp.serviceAccount.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ $ns }}
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $compName }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: {{ printf "%s-%s" $.Chart.Name $.Chart.Version | replace "+" "_" }}
---
{{- end }}

{{- $saName := "" }}
{{- if $comp.serviceAccount.create }}
  {{- $saName = (default (printf "%s-%s" $.Release.Name $compName) $comp.serviceAccount.name) }}
{{- else }}
  {{- $saName = $comp.serviceAccount.name }}
{{- end }}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ printf "%s-%s" $.Release.Name $compName | trunc 63 | trimSuffix "-" }}
  namespace: {{ $ns }}
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $compName }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: {{ printf "%s-%s" $.Chart.Name $.Chart.Version | replace "+" "_" }}
rules:
{{- if $comp.rbac.rules }}
{{ toYaml $comp.rbac.rules | nindent 2 }}
{{- else }}
  - apiGroups: []
    resources: []
    verbs: []
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-%s" $.Release.Name $compName | trunc 63 | trimSuffix "-" }}
  namespace: {{ $ns }}
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $compName }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: {{ printf "%s-%s" $.Chart.Name $.Chart.Version | replace "+" "_" }}
subjects:
  - kind: ServiceAccount
    name: {{ $saName }}
    namespace: {{ $ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ printf "%s-%s" $.Release.Name $compName | trunc 63 | trimSuffix "-" }}
---
{{- end }}
{{- end }}
