{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.controller.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  {{- with .Values.controller.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    iam.gke.io/gcp-service-account: {{ .Values.controller.serviceAccount.gcpServiceAccount }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.controller.serviceAccount.name }}-role
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create","get","list","watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.controller.serviceAccount.name }}-rb
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.controller.serviceAccount.name }}-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.controller.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
{{- end }}
