{{- range $svc, $cfg := .Values }}
{{- if and (kindIs "map" $cfg) (hasKey $cfg "service") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cliscale.fullnameFor" (list $ $svc) }}
  labels:
    {{- include "cliscale.labelsFor" (list $ $svc) | nindent 4 }}
    {{- with $cfg.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $cfg.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $cfg.service.type | default "ClusterIP" }}
  {{- with $cfg.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with $cfg.service.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  selector:
    {{- include "cliscale.selectorLabelsFor" (list $ $svc) | nindent 4 }}
  ports:
    - port: {{ $cfg.service.port | default ($cfg.service.containerPort | default 80) }}
      targetPort: {{ $cfg.service.targetPort | default ($cfg.service.containerPort | default 80) }}
      protocol: TCP
      name: {{ $cfg.service.portName | default "http" }}
    {{- with $cfg.service.extraPorts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
---
{{- end }}
{{- end }}
