{{- range $svc, $cfg := .Values }}
{{- if and (kindIs "map" $cfg) (or (hasKey $cfg "image") (hasKey $cfg "serviceAccount")) }}
{{- $sa := (default dict $cfg.serviceAccount) }}
{{- if or (not (hasKey $sa "create")) ($sa.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "cliscale.fullnameFor" (list $ $svc)) $sa.name }}
  labels:
    {{- include "cliscale.labelsFor" (list $ $svc) | nindent 4 }}
  {{- with $sa.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ default true $sa.automount }}
---
{{- end }}
{{- end }}
{{- end }}
