apiVersion: v1
kind: ServiceAccount
metadata: { name: ws-cli-controller, namespace: ws-cli }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: { name: ws-cli-controller-role, namespace: ws-cli }
rules:
- apiGroups: ["batch"]  resources: ["jobs"]  verbs: ["create","get","list","watch","delete"]
- apiGroups: [""]       resources: ["pods"]  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: { name: ws-cli-controller-rb, namespace: ws-cli }
roleRef: { apiGroup: rbac.authorization.k8s.io, kind: Role, name: ws-cli-controller-role }
subjects: [ { kind: ServiceAccount, name: ws-cli-controller, namespace: ws-cli } ]
