name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-runner:
    name: Test Runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run runner tests
        working-directory: runner
        run: |
          chmod +x test-runner.sh
          ./test-runner.sh

  test-controller:
    name: Test Controller
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cliscale_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: controller/package-lock.json

      - name: Install dependencies
        working-directory: controller
        run: npm ci

      - name: Run tests
        working-directory: controller
        run: npm test

      - name: Build TypeScript
        working-directory: controller
        run: npm run build

      - name: Run database migrations
        working-directory: controller
        run: npm run migrate:latest
        env:
          NODE_ENV: test
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: cliscale_test
          DB_USER: postgres
          DB_PASSWORD: postgres

      - name: Run smoke test
        working-directory: controller
        run: npm run smoke
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: cliscale_test
          DB_USER: postgres
          DB_PASSWORD: postgres
          API_KEY: test-api-key-github-ci
          PORT: 3000
